<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    // Schema::create('events', function (Blueprint $table) {
    //     $table->id();
    //     $table->string('name');
    //     $table->string('description')->nullable();
    //     $table->timestamp('start_date');
    //     $table->timestamp('end_date');
    //     $table->decimal('sign_up_fee', 10, 2);
    //     $table->timestamp('sign_up_deadline');
    //     $table->smallInteger("min_age");
    //     $table->smallInteger("max_age");
    //     $table->smallInteger("max_participants");
    //     $table->foreignId('branch_id')->constrained("branches");
    //     $table->foreignId('type_id')->constrained("event_types");
    //     $table->foreignId('created_by')->constrained("users");
    //     $table->timestamps();
    // });
    public function run(): void
    {
        DB::table('events')->insert([
            [
                'name' => 'Primer Acuatlón Bajo Techo',
                'description' => 'Disfruta del primer evento de natación y carrera en cinta.',
                'start_date' => now()->addDays(8),
                'end_date' => now()->addDays(9),
                'sign_up_fee' => 0.00,
                'sign_up_deadline' => now()->addDays(7),
                'min_age' => 18,
                'max_age' => 60,
                'max_participants' => 100,
                'branch_id' => 1,
                'type_id' => 1,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rodada en Interior de Primavera',
                'description' => 'Evento de ciclismo en espacios cerrados para amantes del deporte.',
                'start_date' => now()->addDays(12),
                'end_date' => now()->addDays(12),
                'sign_up_fee' => 50.00,
                'sign_up_deadline' => now()->addDays(10),
                'min_age' => 16,
                'max_age' => 65,
                'max_participants' => 200,
                'branch_id' => 2,
                'type_id' => 2,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Carrera 5K Día del Padre',
                'description' => 'Celebra el Día del Padre corriendo 5 kilómetros en cinta o exterior.',
                'start_date' => now()->addDays(20),
                'end_date' => now()->addDays(20),
                'sign_up_fee' => 30.00,
                'sign_up_deadline' => now()->addDays(18),
                'min_age' => 15,
                'max_age' => 55,
                'max_participants' => 150,
                'branch_id' => 3,
                'type_id' => 3,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Corre en Cinta Nocturno',
                'description' => 'Corre en cinta con música y luces en una experiencia única.',
                'start_date' => now()->addDays(25),
                'end_date' => now()->addDays(25),
                'sign_up_fee' => 20.00,
                'sign_up_deadline' => now()->addDays(23),
                'min_age' => 18,
                'max_age' => 60,
                'max_participants' => 120,
                'branch_id' => 4,
                'type_id' => 4,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Triatlón In-Doors 2025',
                'description' => 'Compite en el emocionante triatlón bajo techo del año.',
                'start_date' => now()->addDays(30),
                'end_date' => now()->addDays(31),
                'sign_up_fee' => 100.00,
                'sign_up_deadline' => now()->addDays(28),
                'min_age' => 20,
                'max_age' => 50,
                'max_participants' => 50,
                'branch_id' => 5,
                'type_id' => 5,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maratón de Nado con Aletas',
                'description' => 'Participa en el reto de nado con equipo especializado.',
                'start_date' => now()->addDays(40),
                'end_date' => now()->addDays(41),
                'sign_up_fee' => 70.00,
                'sign_up_deadline' => now()->addDays(38),
                'min_age' => 18,
                'max_age' => 65,
                'max_participants' => 80,
                'branch_id' => 6,
                'type_id' => 6,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maratón de Nado con Snorkel',
                'description' => 'Explora un maratón acuático con equipo de snorkel.',
                'start_date' => now()->addDays(45),
                'end_date' => now()->addDays(45),
                'sign_up_fee' => 60.00,
                'sign_up_deadline' => now()->addDays(43),
                'min_age' => 15,
                'max_age' => 55,
                'max_participants' => 70,
                'branch_id' => 1,
                'type_id' => 7,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mega Clase de Macro-Zumba',
                'description' => 'Únete a la clase masiva de zumba más grande del año.',
                'start_date' => now()->addDays(50),
                'end_date' => now()->addDays(50),
                'sign_up_fee' => 25.00,
                'sign_up_deadline' => now()->addDays(48),
                'min_age' => 18,
                'max_age' => 60,
                'max_participants' => 300,
                'branch_id' => 2,
                'type_id' => 8,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Clase de Cortesía Adulto Mayor',
                'description' => 'Especial para celebrar a nuestros adultos mayores.',
                'start_date' => now()->addDays(55),
                'end_date' => now()->addDays(55),
                'sign_up_fee' => 0.00,
                'sign_up_deadline' => now()->addDays(53),
                'min_age' => 60,
                'max_age' => 90,
                'max_participants' => 100,
                'branch_id' => 3,
                'type_id' => 9,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Exhibición Infantil',
                'description' => 'Los más pequeños muestran sus avances en natación.',
                'start_date' => now()->addDays(60),
                'end_date' => now()->addDays(60),
                'sign_up_fee' => 10.00,
                'sign_up_deadline' => now()->addDays(58),
                'min_age' => 1,
                'max_age' => 4,
                'max_participants' => 50,
                'branch_id' => 4,
                'type_id' => 10,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Festival de Clasificación Técnica',
                'description' => 'Competencia especial para niños con habilidades avanzadas.',
                'start_date' => now()->addDays(65),
                'end_date' => now()->addDays(65),
                'sign_up_fee' => 15.00,
                'sign_up_deadline' => now()->addDays(63),
                'min_age' => 6,
                'max_age' => 12,
                'max_participants' => 40,
                'branch_id' => 5,
                'type_id' => 11,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'La Clase de Natación Más Grande del Mundo',
                'description' => 'Rompe el récord en esta clase masiva de natación.',
                'start_date' => now()->addDays(70),
                'end_date' => now()->addDays(70),
                'sign_up_fee' => 0.00,
                'sign_up_deadline' => now()->addDays(68),
                'min_age' => 10,
                'max_age' => 70,
                'max_participants' => 500,
                'branch_id' => 6,
                'type_id' => 12,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Acuatlón Familiar',
                'description' => 'Un evento de natación y carrera en cinta diseñado para toda la familia.',
                'start_date' => now()->addDays(75),
                'end_date' => now()->addDays(75),
                'sign_up_fee' => 40.00,
                'sign_up_deadline' => now()->addDays(73),
                'min_age' => 12,
                'max_age' => 70,
                'max_participants' => 150,
                'branch_id' => 1,
                'type_id' => 1,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rodada In-Doors Express',
                'description' => 'Desafía tus límites en esta rodada corta pero intensa.',
                'start_date' => now()->addDays(80),
                'end_date' => now()->addDays(80),
                'sign_up_fee' => 30.00,
                'sign_up_deadline' => now()->addDays(78),
                'min_age' => 18,
                'max_age' => 65,
                'max_participants' => 100,
                'branch_id' => 2,
                'type_id' => 2,
                'created_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Carrera 5K Primavera',
                'description' => 'Celebra la llegada de la primavera con una carrera al aire libre.',
                'start_date' => now()->addDays(85),
                'end_date' => now()->addDays(85),
                'sign_up_fee' => 25.00,
                'sign_up_deadline' => now()->addDays(83),
                'min_age' => 16,
                'max_age' => 55,
                'max_participants' => 200,
                'branch_id' => 3,
                'type_id' => 3,
                'created_by' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Corre en Cinta Challenge',
                'description' => 'Compite contra otros en un reto de resistencia en cinta.',
                'start_date' => now()->addDays(90),
                'end_date' => now()->addDays(90),
                'sign_up_fee' => 20.00,
                'sign_up_deadline' => now()->addDays(88),
                'min_age' => 18,
                'max_age' => 60,
                'max_participants' => 120,
                'branch_id' => 4,
                'type_id' => 4,
                'created_by' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Triatlón In-Doors Juvenil',
                'description' => 'Una competencia bajo techo diseñada para jóvenes atletas.',
                'start_date' => now()->addDays(95),
                'end_date' => now()->addDays(96),
                'sign_up_fee' => 60.00,
                'sign_up_deadline' => now()->addDays(93),
                'min_age' => 14,
                'max_age' => 18,
                'max_participants' => 50,
                'branch_id' => 5,
                'type_id' => 5,
                'created_by' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maratón de Nado Aletas Avanzado',
                'description' => 'Un desafío especial para nadadores experimentados con aletas.',
                'start_date' => now()->addDays(100),
                'end_date' => now()->addDays(101),
                'sign_up_fee' => 80.00,
                'sign_up_deadline' => now()->addDays(98),
                'min_age' => 20,
                'max_age' => 65,
                'max_participants' => 70,
                'branch_id' => 6,
                'type_id' => 6,
                'created_by' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maratón de Nado con Snorkel Juvenil',
                'description' => 'Un evento de nado con snorkel dirigido a jóvenes talentos.',
                'start_date' => now()->addDays(105),
                'end_date' => now()->addDays(105),
                'sign_up_fee' => 50.00,
                'sign_up_deadline' => now()->addDays(103),
                'min_age' => 12,
                'max_age' => 18,
                'max_participants' => 80,
                'branch_id' => 1,
                'type_id' => 7,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zumbatón Nocturno',
                'description' => 'Una noche de diversión con zumba al ritmo de la música.',
                'start_date' => now()->addDays(110),
                'end_date' => now()->addDays(110),
                'sign_up_fee' => 15.00,
                'sign_up_deadline' => now()->addDays(108),
                'min_age' => 18,
                'max_age' => 55,
                'max_participants' => 250,
                'branch_id' => 2,
                'type_id' => 8,
                'created_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Clase Especial Día de la Madre',
                'description' => 'Celebra a mamá con una clase de cortesía especial.',
                'start_date' => now()->addDays(115),
                'end_date' => now()->addDays(115),
                'sign_up_fee' => 0.00,
                'sign_up_deadline' => now()->addDays(113),
                'min_age' => 18,
                'max_age' => 65,
                'max_participants' => 100,
                'branch_id' => 3,
                'type_id' => 9,
                'created_by' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Competencia Infantil de Natación',
                'description' => 'Un evento diseñado para niños que aman el agua.',
                'start_date' => now()->addDays(120),
                'end_date' => now()->addDays(120),
                'sign_up_fee' => 20.00,
                'sign_up_deadline' => now()->addDays(118),
                'min_age' => 6,
                'max_age' => 12,
                'max_participants' => 60,
                'branch_id' => 4,
                'type_id' => 10,
                'created_by' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Festival de Habilidades Acuáticas',
                'description' => 'Un festival para destacar las habilidades acuáticas de jóvenes talentos.',
                'start_date' => now()->addDays(125),
                'end_date' => now()->addDays(125),
                'sign_up_fee' => 30.00,
                'sign_up_deadline' => now()->addDays(123),
                'min_age' => 10,
                'max_age' => 15,
                'max_participants' => 50,
                'branch_id' => 5,
                'type_id' => 11,
                'created_by' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Clase Mundial de Natación',
                'description' => 'Participa en una clase de natación masiva a nivel mundial.',
                'start_date' => now()->addDays(130),
                'end_date' => now()->addDays(130),
                'sign_up_fee' => 0.00,
                'sign_up_deadline' => now()->addDays(128),
                'min_age' => 8,
                'max_age' => 70,
                'max_participants' => 500,
                'branch_id' => 6,
                'type_id' => 12,
                'created_by' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

    }
}
